### ISSUE TITLE
[Question] How can I run the System.Text.Json scenarios?

### ISSUE THREAD

**Issue by adamsitnik** [aspnet/Benchmarks#1046]
I have tried to run following command (server and client name omitted for brevity and security reasons):

```cmd
-j ../Benchmarks/benchmarks.json.json -n Json --collect-trace
```

And it has worked fine, but from what I can see in the trace this Scenario is using JSON.NET instead of System.Text.Json:

![obraz](https://user-images.githubusercontent.com/6011991/58696778-88820200-8398-11e9-88c4-8f71d7a2197c.png)

After that I have tried to run other scenarios that are described as System.Text.Json:

https://github.com/aspnet/Benchmarks/blob/e270087447bf5217f3472162846a879aa1260531/src/Benchmarks/Configuration/Scenarios.cs#L50-L57

But all of them have failed with really strange error:

```log
AspNetCore version: 3.0.0-preview6-19279-08
CoreCLR version: 3.0.0-preview6.19280.1+41832cedbb2d46362239d2b272964a39ca37cd89
CoreFx version: 3.0.0-preview6.19279.8+e23119d577e644d2c2a25419c88c1181681358e0

Application startup exception: System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Builder.IEndpointConventionBuilder Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllers(Microsoft.AspNetCore.Routing.IEndpointRouteBuilder)'.
   at Benchmarks.Startup.<>c.<Configure>b__9_1(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Benchmarks.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Users\Administrator\AppData\Local\Temp\BenchmarksServer\remhrebd.iqm\benchmarks\src\Benchmarks\Startup.cs:line 355
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

The type that throws has not been change for more than a month: https://github.com/aspnet/AspNetCore/commits/master/src/Mvc/Mvc.Core/src/Builder/ControllerEndpointRouteBuilderExtensions.cs

I tried to change the dotnet/aspnet version, but without any luck.

@sebastienros @pranavkm am I doing something wrong?

**Comment by sebastienros** [comment]
You are right, only `MvcJson` has been moved, I will do the other ones.

For the error, try using `--sdk Latest` because otherwise the build will use whatever version of aspnet if was bundled with, and it has had a breaking changes since then. By using the latest sdk the code in the benchmarks and the aspnet version from the sdk will be compatible.

**Comment by adamsitnik** [comment]
```cmd
--sdk Latest
```

Gives me:

```log
[07:46:26.202] Job submitted, waiting...
[07:46:36.332] Job failed on benchmark server, stopping...
Job failed at runtime
```

**Comment by sebastienros** [comment]
--sdk latest --no-global-json --server-timeout 00:20:00

Or more if the benchmarks take longer. This is why I use job=short too, I pasted the example in teams earlier

Sent from Outlook
________________________________
