### ISSUE TITLE
MvcJsonInput2k is broken

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1141]
The script file cannot be uploaded anymore.

```
[08:29:37.027] System.InvalidOperationException: An error occured while uploading a file. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 415 (Unsupported Media Type).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BenchmarksDriver.Program.UploadScriptAsync(String filename, ClientJob clientJob, Uri clientJobUri) in /var/jenkins_home/workspace/trend_citrine_windows/src/BenchmarksDriver/Program.cs:line 2264
   --- End of inner exception stack trace ---
   at BenchmarksDriver.Program.UploadScriptAsync(String filename, ClientJob clientJob, Uri clientJobUri) in /var/jenkins_home/workspace/trend_citrine_windows/src/BenchmarksDriver/Program.cs:line 2267
   at BenchmarksDriver.Program.RunClientJob(String scenarioName, Uri clientUri, Uri serverJobUri, String serverBenchmarkUri, CommandOption scriptFileOption) in /var/jenkins_home/workspace/trend_citrine_windows/src/BenchmarksDriver/Program.cs:line 2313
   at BenchmarksDriver.Program.RunClientJob(String scenarioName, Uri clientUri, Uri serverJobUri, String serverBenchmarkUri, CommandOption scriptFileOption) in /var/jenkins_home/workspace/trend_citrine_windows/src/BenchmarksDriver/Program.cs:line 2425
   at BenchmarksDriver.Program.Run(Uri serverUri, Uri clientUri, String sqlConnectionString, ServerJob serverJob, String session, String description, Int32 iterations, Int32 exclude, String shutdownEndpoint, TimeSpan span, List`1 downloadFiles, Boolean fetch, String fetchDestination, Boolean collectR2RLog, String traceDestination, CommandOption outputFileOption, CommandOption sourceOption, CommandOption scriptFileOption, CommandOption markdownOption, CommandOption writeToFileOption, Nullable`1 requiredOperatingSystem, CommandOption saveOption, CommandOption diffOption) in /var/jenkins_home/workspace/trend_citrine_windows/src/BenchmarksDriver/Program.cs:line 1434
```

**Comment by sebastienros** [comment]
I assume the server endpoint needs to be updated since we migrated to 3.0 preview7. Or the request from the driver.
