### ISSUE TITLE
Method not found: 'Microsoft.Framework.Runtime.Library Microsoft.Framework.Runtime.ILibraryManager.GetLibraryInformation(System.String)'.

### ISSUE THREAD

**Issue by cheers00** [aspnet/benchmarks#13]
I wanted to try this but when I run Benchmarks asp vnext web app, I get the following error in visual studio. I get the same error with dnx with and beta5 (clr\coreclr x86\x64).

I have the latest VS 2015 and beta5 and I am not behind proxy. dnu restore works just fine.

```
C:\Projects\git\benchmarks\src\Benchmarks>dnx . web
System.TypeLoadException: Could not load type 'Microsoft.Framework.Runtime.IRuntimeServices' from assembly 'Microsoft.Fr
amework.Runtime.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.AspNet.Hosting.WebHostBuilder.BuildHostingServices()
   at Microsoft.AspNet.Hosting.WebHostBuilder.Build()
   at Microsoft.AspNet.Hosting.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider s
erviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

**Comment by davidfowl** [comment]
You can't use beta5, we run the benchmarks on the latest stuff

**Comment by cheers00** [comment]
I am using beta5. The latest one.

**Comment by cheers00** [comment]
Thanks. I will try the latest beta unstable.
