### ISSUE TITLE
Basic.* scenarios disabled

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1313]
Due to this issue:

```
[08:48:29.548] Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
[08:48:29.548]  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'hello_world.people' doesn't exist
[08:48:29.548]  ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Table 'hello_world.people' doesn't exist
[08:48:29.548]    at MySqlConnector.Core.ServerSession.TryAsyncContinuation(Task`1 task) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1214
[08:48:29.548]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[08:48:29.548]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[08:48:29.548] --- End of stack trace from previous location where exception was thrown ---
[08:48:29.549]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[08:48:29.549] --- End of stack trace from previous location where exception was thrown ---
[08:48:29.549]    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
[08:48:29.549]    at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
[08:48:29.549]    at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 300
[08:48:29.549]    at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 293
[08:48:29.549]    at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 52
[08:48:29.549]    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
[08:48:29.549]    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
[08:48:29.549]    --- End of inner exception stack trace ---
[08:48:29.549]    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
[08:48:29.549]    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
[08:48:29.549]    at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
[08:48:29.549]    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
[08:48:29.549]    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
[08:48:29.549]    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
[08:48:29.549]    at BasicViews.Controllers.HomeController.Index(Person person) in /tmp/BenchmarksServer/u1flufpx.nci/AspNetCore/src/Mvc/benchmarkapps/BasicViews/Controllers/HomeController.cs:line 35
[08:48:29.549]    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
[08:48:29.549]    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
[08:48:29.549]    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
[08:48:29.550]    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
[08:48:29.550]    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
[08:48:29.550]    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
[08:48:29.550]    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
[08:48:29.550]    at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.SetRoutingAndContinue(HttpContext httpContext)
[08:48:29.550]    at BasicViews.Startup.<>c__DisplayClass6_1.<<Configure>b__4>d.MoveNext() in /tmp/BenchmarksServer/u1flufpx.nci/AspNetCore/src/Mvc/benchmarkapps/BasicViews/Startup.cs:line 116
```

**Comment by ajcvickers** [comment]
@sebastienros Where are we using MySql? It certainly won't work with anything 3.0 until there is an updated provider.
/cc @roji @divega

**Comment by sebastienros** [comment]
Figured. These are some scenarios that @dougbu  wrote a while ago. I usually either ignore or dsiable them whenever mysql driver are no more aligned. I just create this issue to keep track.

**Comment by roji** [comment]
Unless I'm mistaken, MySql.Data.MySqlClient is the official Oracle ADO driver, not EF Core - so there's no reason it wouldn't work (although we should be testing on https://github.com/mysql-net/MySqlConnector which should be much more performant).

For EF Core yeah, as @ajcvickers wrote we'd need the Pomelo provider ported to 3.0...

**Comment by ajcvickers** [comment]
@roji The stack trace has `Pomelo.EntityFrameworkCore.MySql`

**Comment by roji** [comment]
Right, missed that...
