### ISSUE TITLE
updates/ef: Invalid operation. The connection is closed.

### ISSUE THREAD

**Issue by mikeharder** [aspnet/benchmarks#163]
# Repro Steps
1. Enable error logging in server: `loggerFactory.AddConsole(LogLevel.Error);`
2. Server; `dotnet bin\Release\netcoreapp1.1\Benchmarks.dll scenarios=db server.urls=http://+:8080 noninteractive=true`
3. Load Generator: `wrk -c 256 -t 32 -d 10 http://server-ip-or-name:8080/updates/ef?queries=20`
4. May need to run load generator many times to get exception

# Exception
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HL12TONOKVJ0": An unhandled exception was thrown by the application.
System.InvalidOperationException: Invalid operation. The connection is closed.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__107_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.<First_>d__164`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Data.EfDb.<LoadMultipleUpdatesRows>d__6.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Data\EfDb.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.MultipleUpdatesEfMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\MultipleUpdatesEfMiddleware.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.MultipleUpdatesDapperMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\MultipleUpdatesDapperMiddleware.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.MultipleUpdatesRawMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\MultipleUpdatesRawMiddleware.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.MultipleQueriesEfMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\MultipleQueriesEfMiddleware.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.MultipleQueriesDapperMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\MultipleQueriesDapperMiddleware.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.MultipleQueriesRawMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\MultipleQueriesRawMiddleware.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.SingleQueryEfMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\SingleQueryEfMiddleware.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.SingleQueryDapperMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\SingleQueryDapperMiddleware.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Benchmarks.Middleware.SingleQueryRawMiddleware.<Invoke>d__4.MoveNext() in C:\Git\Benchmarks\src\Benchmarks\Middleware\SingleQueryRawMiddleware.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
```

**Comment by mikeharder** [comment]
@anpete, @divega: What is the recommended way to handle this in EF?

**Comment by divega** [comment]
Cc @AndriySvyryd and @smitpatel in case they can see any clues in the stack trace.

**Comment by mikeharder** [comment]
Maybe we just need to enable the proper `ExecutionStrategy`?

https://msdn.microsoft.com/en-us/library/dn456835(v=vs.113).aspx

Is it recommended to use the `SqlAzureExecutionStrategy`?  Is it recommended to use this strategy for both SQL in a VM and the SQL Azure service?  I was using SQL in a VM at the time of the exception, but the benchmark could be run with either flavor of SQL.

**Comment by mikeharder** [comment]
We should also handle similar errors from PostgreSQL.

**Comment by AndriySvyryd** [comment]
@mikeharder We have made some changes in the code that handles connection closing, so this might be a regression. Was this working with 1.0.1 or 1.1?
As for the execution strategy it is perfectly reasonable to enable it for SQL in VM, see [Connection Resiliency](https://docs.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency), though this exception won't be retried be default, you would probably need to create a derived execution strategy to do it. The same can be done for PostgreSQL.

**Comment by mikeharder** [comment]
@AndriySvyryd: I'm not sure if this is a regression.  I've actually only seen this exception once.  Do you know if there's a way to reliably repro this exception?  I tried pausing or stopping the SQL service on the VM, but this causes different exceptions.

If we can't repro this reliably, I'm fine with just closing this issue and waiting to see if it happens again.

**Comment by mikeharder** [comment]
Also, why wouldn't this exception be retried by default?  Connection closed seems like a standard reason to retry.

**Comment by AndriySvyryd** [comment]
@mikeharder I've never seen this exception, usually the connection breaks while one of the SqlClient methods are running resulting in a more descriptive exception. But assuming there are no new regressions and that the connection is not getting closed by a different thread, the above stack trace indicates that the connection has been broken between the `.Open` and `.Execute` calls, which would be an extremely rare occurrence.
If this is the case and we can identify this exception reliably we could indeed retry on it by default.

**Comment by mikeharder** [comment]
Closing until this repros more often.  We don't really need connection resiliency since this is a short-lived benchmark that usually shouldn't have connections closing.
