### ISSUE TITLE
Platform benchmarks failing for .NET6.0 (System.TypeInitializationException)

### ISSUE THREAD

**Issue by L2** [aspnet/Benchmarks#1699]
For example:

```
crank --config "https://raw.githubusercontent.com/aspnet/Benchmarks/master/scenarios/platform.benchmarks.yml" --config foo --application.framework net6.0 --application.collectCounters true --application.startTimeout '00:15:00' --profile bar --scenario caching
```
Output:
```
[STDERR] Unhandled exception. System.TypeInitializationException: The type initializer for 'PlatformBenchmarks.BenchmarkApplication' threw an exception.
[STDERR]  ---> System.TypeLoadException: Method 'get_GeneratedSerializerOptions' in type 'JsonContext' from assembly 'PlatformBenchmarks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
[STDERR]    at PlatformBenchmarks.BenchmarkApplication..cctor()
[STDERR]    --- End of inner exception stack trace ---
[STDERR]    at PlatformBenchmarks.BenchmarkApplication.get_ApplicationName() in C:\Users\foo\AppData\Local\Temp\benchmarks-agent\benchmarks-server-bar\foo-bar\benchmarks\src\BenchmarksApps\Kestrel\PlatformBenchmarks\BenchmarkApplication.cs:line 17
[STDERR]    at PlatformBenchmarks.Program.Main(String[] args) in C:\Users\foo\AppData\Local\Temp\benchmarks-agent\benchmarks-server-bar\foo-bar\benchmarks\src\BenchmarksApps\Kestrel\PlatformBenchmarks\Program.cs:line 25
[STDERR]    at PlatformBenchmarks.Program.<Main>(String[] args)
```

Changing the framework to `net5.0` seems to work fine.

I'm using the latest `crank` and `crank-agent`: `version 0.2.0-alpha.21457.1`

Thanks

**Comment by sebastienros** [comment]
In net6.0 there is current an issue with recent changes (from this WE) that are breaking on rc2 and need to be applied in this repository. https://github.com/dotnet/runtime/pull/59042

/cc @layomia

**Comment by L2** [comment]
Thanks @sebastienros and @layomia , is there anything I can do to help resolve this?

**Comment by sebastienros** [comment]
It's fixed, you need to pickup the latest agent code.

**Comment by L2** [comment]
Thanks @sebastienros , do you know if the .nuget package for crank-agent will be updated as well?

```
dotnet tool update -g Microsoft.Crank.Agent --version "0.2.0-*" 
```

**Comment by sebastienros** [comment]
My CI is currently broken (macOS issues). Will update the thread when it's fixed.

**Comment by sebastienros** [comment]
It's on NuGet now.

**Comment by L2** [comment]
Thanks again
