### ISSUE TITLE
Wrong connection string for npgsql

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1812]
Recently broken:

```
Database: PostgreSql
ConnectionString: Server=;Database=hello_world;User Id=benchmarkdbuser;Password=benchmarkdbpass;Maximum Pool Size=18;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Buffer Threshold Bytes=1000
[STDERR] Unhandled exception. System.ArgumentException: Host can't be null
[STDERR]    at Npgsql.NpgsqlConnectionStringBuilder.PostProcessAndValidate()
[STDERR]    at Npgsql.NpgsqlSlimDataSourceBuilder.PrepareConfiguration()
[STDERR]    at Npgsql.NpgsqlSlimDataSourceBuilder.Build()
[STDERR]    at Npgsql.NpgsqlDataSourceBuilder.Build()
[STDERR]    at Npgsql.NpgsqlDataSource.Create(String connectionString)
[STDERR]    at PlatformBenchmarks.RawDb..ctor(ConcurrentRandom random, AppSettings appSettings) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-8092\mq0y5lkj.sc4\benchmarks\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\Data\RawDb.cs:line 32
[STDERR]    at PlatformBenchmarks.Program.BuildWebHost(String[] args) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-8092\mq0y5lkj.sc4\benchmarks\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\Program.cs:line 75
[STDERR]    at PlatformBenchmarks.Program.Main(String[] args) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-8092\mq0y5lkj.sc4\benchmarks\src\BenchmarksApps\TechEmpower\PlatformBenchmarks\Program.cs:line 37
[STDERR]    at PlatformBenchmarks.Program.<Main>(String[] args)
```

https://dev.azure.com/dnceng/internal/_build/results?buildId=2134528&view=logs&j=d3806cb9-9f29-58a2-f37f-9b640ae897dc&t=0464fd43-95cd-5f5a-6725-81098dcbe5d0

**Comment by sebastienros** [comment]
I can see that the server is not set. But I believe this should not even run for benchmarks that do not access the database, so a recent change removed the check probably.
