### ISSUE TITLE
Platform database benchmarks broken

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1822]
```
Error trying to populate database cache: System.ArgumentOutOfRangeException: 'dueTime' must be less than or equal to '4294967294'. (Parameter 'dueTime')
Actual value was 4294967295.
  at System.ArgumentOutOfRangeException.ThrowGreater[T](String paramName, T value, T other)
  at System.Threading.TimerQueueTimer.GetMilliseconds(TimeSpan time, String parameter)
  at System.Threading.TimerQueueTimer.Change(TimeSpan dueTime, TimeSpan period)
  at System.Threading.CancellationTokenSource.CancelAfter(UInt32 millisecondsDelay)
  at System.Threading.CancellationTokenSource.CancelAfter(TimeSpan delay)
  at Npgsql.Util.ResettableCancellationTokenSource.Stop()
  at Npgsql.Internal.NpgsqlWriteBuffer.Flush(Boolean async, CancellationToken cancellationToken)
  at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
  at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
  at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
  at Npgsql.PoolingDataSource.OpenNewConnector(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
  at Npgsql.PoolingDataSource.<Get>g__RentAsync|28_0(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
  at Npgsql.NpgsqlConnection.<>c__DisplayClass166_0.<<StartBindingScope>g__StartBindingScopeAsync|0>d.MoveNext()
```

**Comment by vonzshik** [comment]
There was a change around timers in https://github.com/dotnet/runtime/pull/83604. Might be the reason?

**Comment by sebastienros** [comment]
@vonzshik definitely related, this exception is a new behavior from this PR, thanks

**Comment by sebastienros** [comment]
This seems to be triggered by this https://github.com/npgsql/npgsql/blob/43a2e983f41aced973d7071eb0fdbea1ca7a8773/src/Npgsql/Util/ResettableCancellationTokenSource.cs#L169

**Comment by vonzshik** [comment]
Yep. Also notice that it casts from TimeSpan to UInt32 - this probably is the reason:

```
at System.Threading.CancellationTokenSource.CancelAfter(UInt32 millisecondsDelay)
  at System.Threading.CancellationTokenSource.CancelAfter(TimeSpan delay)
  at Npgsql.Util.ResettableCancellationTokenSource.Stop()
```

**Comment by sebastienros** [comment]
Agreed, because the checks are the same (ArgumentOutOfRangeException.ThrowIfGreaterThan)

**Comment by vonzshik** [comment]
I took a closer look. There is a thing called [UnsignedInfinite](https://github.com/dotnet/runtime/blob/5d88ff404de77d78e07ad3de7fa2af270332da22/src/libraries/System.Private.CoreLib/src/System/Threading/Timeout.cs#L14) which is used by the timer as `infinite` timeout. And it seems because [TimerQueueTimer.Change](https://github.com/dotnet/runtime/commit/5d88ff404de77d78e07ad3de7fa2af270332da22#diff-ca0e15ba4d75ab4c7ce9b34d870658ec3d507a6e88739138e9751b7338b4171dL522-R539) now accepts `TimeSpan` and tries to validate it (without accounting for `uint` to `TimeSpan` conversion) we get the exception.

**Comment by sebastienros** [comment]
Can you comment on the PR to let them know?

**Comment by vonzshik** [comment]
Sure.

**Comment by DamianEdwards** [comment]
This is fixed now.
