### ISSUE TITLE
Failing pipeline, Native AOT Intel Windows

### ISSUE THREAD

**Issue by mgravell** [aspnet/Benchmarks#1830]
from build-ops; consistently failing in "Native Aot Intel Windows" with (in multiple sub-tests):

``` txt
[STDERR] Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[STDERR]    at System.RuntimeTypeHandle.RegisterCollectibleTypeDependency(System.RuntimeType, System.Reflection.RuntimeAssembly)
[STDERR]    at System.Reflection.TypeNameParser.GetTypeReferencedByCustomAttribute(System.String, System.Reflection.RuntimeModule)
[STDERR]    at System.Reflection.CustomAttributeTypedArgument..ctor(System.Reflection.RuntimeModule, System.Reflection.CustomAttributeEncodedArgument)
[STDERR]    at System.Reflection.RuntimeCustomAttributeData.get_ConstructorArguments()
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetDynamicallyAccessedMemberTypes(System.Type)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.ValidateTrimmingAnnotations(System.Type, System.Type[], System.Type, System.Type[])
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(System.Collections.Generic.ICollection`1<Microsoft.Extensions.DependencyInjection.ServiceDescriptor>, Microsoft.Extensions.DependencyInjection.ServiceProviderOptions)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection, Microsoft.Extensions.DependencyInjection.ServiceProviderOptions)
[STDERR]    at Microsoft.Extensions.Hosting.HostApplicationBuilder.Build()
[STDERR]    at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
[STDERR]    at Program.<Main>$(System.String[])
```

There's also a bunch of `Could not find an agent named 'db'.` failures, which seem bad but *less bad*.

**Comment by sebastienros** [comment]
@eerhardt Can you suggest someone who should look into this?

I will look into the 'db' issue, probably related to profiles configuration.

**Comment by DamianEdwards** [comment]
Is this from perf runs? Could be due to mismatch between runtime and native AOT tool chain assuming they're all rolling forward independently.

**Comment by eerhardt** [comment]
I've opened https://github.com/dotnet/runtime/issues/84372 for the AccessViolationException. It looks like a regression in dotnet/runtime.
