### ISSUE TITLE
H3 benchmarks are broken

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Benchmarks#1894]
```

[STDERR]  ---> System.InvalidOperationException: Unable to bind an HTTP/3 endpoint. This could be because QUIC has not been configured using UseQuic, or the platform doesn't support QUIC or HTTP/3.
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
[STDERR]    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
[STDERR]    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
[STDERR]    at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[STDERR]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
[STDERR]    at HttpClientBenchmarks.Program.RunKestrel() in /tmp/benchmarks-agent/benchmarks-server-1/a1bc02jk.u2r/src/BenchmarksApps/HttpClientBenchmarks/Servers/Kestrel/Program.cs:line 113
[STDERR]    at HttpClientBenchmarks.Program.<>c.<Main>b__2_3(ServerOptions options) in /tmp/benchmarks-agent/benchmarks-server-1/a1bc02jk.u2r/src/BenchmarksApps/HttpClientBenchmarks/Servers/Kestrel/Program.cs:line 33
[STDERR]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[STDERR]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[STDERR]    --- End of inner exception stack trace ---
[STDERR]    at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
[STDERR]    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[STDERR]    at System.Delegate.DynamicInvokeImpl(Object[] args)
[STDERR]    at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
[STDERR]    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__20_0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseVersionOption>b__0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__19_0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
[STDERR] --- End of stack trace from previous location ---
[STDERR]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

/cc @CarnaViire

**Comment by sebastienros** [comment]
If that helps the benchmarks seems to have stopped working around 8/11

![image](https://github.com/aspnet/Benchmarks/assets/1165805/d5396b67-9691-4164-bcdd-b32e6a6cfd4d)

**Comment by CarnaViire** [comment]
I'll put up a fix. Most possibly, we need to update MsQuic package

**Comment by sebastienros** [comment]
Still failing, same stack trace

**Comment by sebastienros** [comment]
Wait, maybe this machine is not updating automatically.

**Comment by sebastienros** [comment]
That was it, charts are updated again. It might be slower though.
