### ISSUE TITLE
Benchmarks job fails - no reason specified

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/benchmarks#242]
Most recent run of benchmarks failed. Reasons unclear.  A few dozen benchmarks had completed when it suddenly died with this error:

http://aspnetci/viewLog.html?buildTypeId=Lite_Benchmarks_BenchmarkTests&buildId=194546

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Server job failed) ---> System.InvalidOperationException: Server job failed
[21:23:26]     at BenchmarkDriver.Program.<Run>d__7.MoveNext() in C:\BuildAgent\work\ddf597b0fdcad259\src\BenchmarksDriver\Program.cs:line 337
[21:23:26]     --- End of inner exception stack trace ---
[21:23:26]     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[21:23:26]     at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[21:23:26]     at BenchmarkDriver.Program.<>c__DisplayClass6_0.<Main>b__0() in C:\BuildAgent\work\ddf597b0fdcad259\src\BenchmarksDriver\Program.cs:line 286
```

**Comment by mikeharder** [comment]
Thanks for filing.  Benchmarks currently isn't very good about reporting errors back to the driver, so you need to log onto the server to get the real error message.  In this case, the issue is that breaking changes were made in kestrel@dev but not kestrel@feature/dev-si, and Benchmarks reacted to the breaking change, so Benchmarks is now compatible with kestrel@dev but not kestrel@feature/dev-si.

To fix this, we're going to stop testing kestrel@feature/dev-si.

**Comment by mikeharder** [comment]
Fixed: https://github.com/aspnet/benchmarks/commit/3a54b0dc5b3e69deeef8dc827ec71e34e0aab6a4
